name: Python Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]  # Support multiple Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build and Test Docker container
      run: |
        # Build the Docker image
        docker build -t flask-app .
        
        # Run the Flask app container and expose it
        docker run -d -p 5000:5000 flask-app

        # Run the tests using pytest inside the Docker container
        docker run --rm flask-app pytest --maxfail=1 --disable-warnings -v

    - name: Lint with flake8
      run: |
        # Run flake8 to lint the code
        docker run --rm flask-app flake8 .
        
    - name: Deploy (optional step for deploying after tests)
      run: |
        echo "Deploy your application here"
        # Add your deployment logic here, such as pushing to a server or Docker registry
